config/routes.rb
Rails.application.routes.draw do






  get 'enlaces/index'

  get 'enlaces/ver'

  get 'enlaces/crear'

  get 'enlaces/eliminar'

  get 'directorio/index'

  get 'directorio/crear'

  get 'directorio/editar'

  get 'directorio/ver'

  get 'perfil/index'

  get 'perfil/crear'

  get 'perfil/editar'

  get 'perfil/ver'

  get 'newsletter/index'

  get 'newsletter/crear'

  get 'newsletter/editar'

  get 'newsletter/ver'

  get 'conocimiento/index'

  get 'conocimiento/crear'

  get 'conocimiento/editar'

  get 'conocimiento/ver'

  get 'archivos/index'

  get 'archivos/crear'

  get 'archivos/editar'

  get 'archivos/ver'

  get 'roles/index'

  get 'roles/crear'

  get 'roles/editar'

  get 'roles/ver'

  get 'usuarios/index'

  get 'usuarios/crear'

  get 'usuarios/editar'

  get 'usuarios/ver'

  get 'poli/index'

  get 'poli/crear'

  get 'poli/editar'

  get 'poli/ver'

  get 'politica/crear'

  get 'politica/editar'

  get 'politica/ver'

  get 'login/index'

  devise_for :users
  devise_for :admins
  resources :actividades_minuta
  resources :objetivo_minuta
  resources :participantes_minuta
  resources :minuta
  get 'minuta/index'

  get 'document/index'

  get 'app/index'
  root 'app#index'
  get 'documentos' => 'document#index', as: :document
  get 'checklist' => 'checklist#index', as: :checklist
  get 'galeria' => 'galeria#index', as: :galeria
  get 'login' => 'login#index', as: :login
  get 'editar/minuta' => 'minuta#editar', as: :editar
  get 'ver/minuta' => 'minuta#ver', as: :ver
  get 'procedimientos' => 'politica#index', as: :politica
  get 'procedimientos/crear' => 'politica#crear', as: :crear
  get 'editar/procedimiento' => 'politica#editar', as: :editar_procedimientos
  get 'ver/procedimiento' => 'politica#ver', as: :ver_procedimientos
  get 'politicas' => 'poli#index', as: :poli
  get 'politicas/crear' => 'poli#crear', as: :crear_politica
  get 'editar/politica' => 'poli#editar', as: :editar_politicas
  get 'ver/politica' => 'poli#ver', as: :ver_politicas
  get 'checklist/crear' => 'checklist#crear', as: :crear_checklist
  get 'editar/checklist' => 'checklist#editar', as: :editar_checklist
  get 'ver/checklist' => 'checklist#ver', as: :ver_checklist
  get 'usuarios' => 'usuarios#index', as: :usuarios
  get 'usuarios/crear' => 'usuarios#crear', as: :crear_usuarios
  get 'editar/usuarios' => 'usuarios#editar', as: :editar_usuarios
  get 'ver/usuarios' => 'usuarios#ver', as: :ver_usuarios
  get 'roles' => 'roles#index', as: :roles
  get 'rol/crear' => 'roles#crear', as: :crear_roles
  get 'editar/rol' => 'roles#editar', as: :editar_roles
  get 'ver/rol' => 'roles#ver', as: :ver_roles
  get 'archivos' => 'archivos#index', as: :archivos
  get 'archivos/crear' => 'archivos#crear', as: :crear_archivos
  get 'editar/archivos' => 'archivos#editar', as: :editar_archivos
  get 'ver/archivos' => 'archivos#ver', as: :ver_archivos
  get 'perfil' => 'perfil#index', as: :perfil
  get 'ver/perfil' => 'perfil#ver', as: :ver_perfil
  get 'directorio' => 'directorio#index', as: :directorio
  get 'knowledge_base' => 'conocimiento#index', as: :knowledge_base
  get 'ver/knowledge_base' => 'conocimiento#ver', as: :ver_knowledge_base
  get 'enlaces' => 'enlaces#index', as: :enlaces
  get 'ver/enlaces' => 'enlaces#ver', as: :ver_enlaces
  get 'newsletter' => 'newsletter#index', as: :newsletter
  get 'ver/newsletter' => 'newsletter#ver', as: :ver_newsletter
  
  namespace :api do
      namespace :v1 do
        resources :get_user, path: "get_user"
      end
    end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/minutum.rb
class Minutum < ApplicationRecord
end

app/models/objetivo_minutum.rb
class ObjetivoMinutum < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/actividades_minuta_controller.rb
class ActividadesMinutaController < ApplicationController
  before_action :set_actividades_minutum, only: [:show, :edit, :update, :destroy]

  # GET /actividades_minuta
  # GET /actividades_minuta.json
  def index
    @actividades_minuta = ActividadesMinutum.all
  end

  # GET /actividades_minuta/1
  # GET /actividades_minuta/1.json
  def show
  end

  # GET /actividades_minuta/new
  def new
    @actividades_minutum = ActividadesMinutum.new
  end

  # GET /actividades_minuta/1/edit
  def edit
  end

  # POST /actividades_minuta
  # POST /actividades_minuta.json
  def create
    @actividades_minutum = ActividadesMinutum.new(actividades_minutum_params)

    respond_to do |format|
      if @actividades_minutum.save
        format.html { redirect_to @actividades_minutum, notice: 'Actividades minutum was successfully created.' }
        format.json { render :show, status: :created, location: @actividades_minutum }
      else
        format.html { render :new }
        format.json { render json: @actividades_minutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /actividades_minuta/1
  # PATCH/PUT /actividades_minuta/1.json
  def update
    respond_to do |format|
      if @actividades_minutum.update(actividades_minutum_params)
        format.html { redirect_to @actividades_minutum, notice: 'Actividades minutum was successfully updated.' }
        format.json { render :show, status: :ok, location: @actividades_minutum }
      else
        format.html { render :edit }
        format.json { render json: @actividades_minutum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /actividades_minuta/1
  # DELETE /actividades_minuta/1.json
  def destroy
    @actividades_minutum.destroy
    respond_to do |format|
      format.html { redirect_to actividades_minuta_url, notice: 'Actividades minutum was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_actividades_minutum
      @actividades_minutum = ActividadesMinutum.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def actividades_minutum_params
      params.require(:actividades_minutum).permit(:minutaToken, :responsable, :asunto, :actividad, :coResponsable, :fechaCompromiso, :userid)
    end
end

app/helpers/actividades_minuta_helper.rb
module ActividadesMinutaHelper
end

app/helpers/app_helper.rb
module AppHelper
end

app/helpers/archivos_helper.rb
module ArchivosHelper
end

app/helpers/checklist_helper.rb
module ChecklistHelper
end

app/helpers/directorio_helper.rb
module DirectorioHelper
end

app/helpers/document_helper.rb
module DocumentHelper
end

app/helpers/enlaces_helper.rb
module EnlacesHelper
end

app/helpers/galeria_helper.rb
module GaleriaHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/minuta_helper.rb
module MinutaHelper
end

app/helpers/newsletter_helper.rb
module NewsletterHelper
end

app/helpers/perfil_helper.rb
module PerfilHelper
end

app/helpers/poli_helper.rb
module PoliHelper
end

app/helpers/politica_helper.rb
module PoliticaHelper
end

app/helpers/roles_helper.rb
module RolesHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/actividades_minuta/_form.html.erb
<%= form_with(model: actividades_minutum, local: true) do |form| %>
  <% if actividades_minutum.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(actividades_minutum.errors.count, "error") %> prohibited this actividades_minutum from being saved:</h2>

      <ul>
      <% actividades_minutum.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :minutaToken %>
    <%= form.text_field :minutaToken, id: :actividades_minutum_minutaToken %>
  </div>

  <div class="field">
    <%= form.label :responsable %>
    <%= form.text_field :responsable, id: :actividades_minutum_responsable %>
  </div>

  <div class="field">
    <%= form.label :asunto %>
    <%= form.text_field :asunto, id: :actividades_minutum_asunto %>
  </div>

  <div class="field">
    <%= form.label :actividad %>
    <%= form.text_area :actividad, id: :actividades_minutum_actividad %>
  </div>

  <div class="field">
    <%= form.label :coResponsable %>
    <%= form.text_field :coResponsable, id: :actividades_minutum_coResponsable %>
  </div>

  <div class="field">
    <%= form.label :fechaCompromiso %>
    <%= form.text_field :fechaCompromiso, id: :actividades_minutum_fechaCompromiso %>
  </div>

  <div class="field">
    <%= form.label :userid %>
    <%= form.text_field :userid, id: :actividades_minutum_userid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/actividades_minuta/edit.html.erb
<h1>Editing Actividades Minutum</h1>

<%= render 'form', actividades_minutum: @actividades_minutum %>

<%= link_to 'Show', @actividades_minutum %> |
<%= link_to 'Back', actividades_minuta_path %>

app/views/actividades_minuta/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Actividades Minuta</h1>

<table>
  <thead>
    <tr>
      <th>Minutatoken</th>
      <th>Responsable</th>
      <th>Asunto</th>
      <th>Actividad</th>
      <th>Coresponsable</th>
      <th>Fechacompromiso</th>
      <th>Userid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @actividades_minuta.each do |actividades_minutum| %>
      <tr>
        <td><%= actividades_minutum.minutaToken %></td>
        <td><%= actividades_minutum.responsable %></td>
        <td><%= actividades_minutum.asunto %></td>
        <td><%= actividades_minutum.actividad %></td>
        <td><%= actividades_minutum.coResponsable %></td>
        <td><%= actividades_minutum.fechaCompromiso %></td>
        <td><%= actividades_minutum.userid %></td>
        <td><%= link_to 'Show', actividades_minutum %></td>
        <td><%= link_to 'Edit', edit_actividades_minutum_path(actividades_minutum) %></td>
        <td><%= link_to 'Destroy', actividades_minutum, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Actividades Minutum', new_actividades_minutum_path %>

app/views/actividades_minuta/new.html.erb
<h1>New Actividades Minutum</h1>

<%= render 'form', actividades_minutum: @actividades_minutum %>

<%= link_to 'Back', actividades_minuta_path %>

app/views/actividades_minuta/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Minutatoken:</strong>
  <%= @actividades_minutum.minutaToken %>
</p>

<p>
  <strong>Responsable:</strong>
  <%= @actividades_minutum.responsable %>
</p>

<p>
  <strong>Asunto:</strong>
  <%= @actividades_minutum.asunto %>
</p>

<p>
  <strong>Actividad:</strong>
  <%= @actividades_minutum.actividad %>
</p>

<p>
  <strong>Coresponsable:</strong>
  <%= @actividades_minutum.coResponsable %>
</p>

<p>
  <strong>Fechacompromiso:</strong>
  <%= @actividades_minutum.fechaCompromiso %>
</p>

<p>
  <strong>Userid:</strong>
  <%= @actividades_minutum.userid %>
</p>

<%= link_to 'Edit', edit_actividades_minutum_path(@actividades_minutum) %> |
<%= link_to 'Back', actividades_minuta_path %>